(page-linear) begin
(page-linear) init: cksum=3115322833
(page-linear) shuffle 0: cksum=1691062564
(page-linear) shuffle 1: cksum=1973575879
(page-linear) shuffle 2: cksum=1647619479
(page-linear) shuffle 3: cksum=96566261
(page-linear) shuffle 4: cksum=3885786467
(page-linear) shuffle 5: cksum=3022003332
(page-linear) shuffle 6: cksum=3614934266
(page-linear) shuffle 7: cksum=2704001777
(page-linear) shuffle 8: cksum=735775156
(page-linear) shuffle 9: cksum=1864109763
(page-linear) end
