SRCDIR = ../..

# Test programs to compile, and a list of sources for each.
# To add a new test, put its name on the PROGS list
# and then add a name_SRC line that lists its source files.
PROGS = bubsort echo halt insult lineup ls matmult mkdir recursor shell
bubsort_SRC = bubsort.c
echo_SRC = echo.c
halt_SRC = halt.c
insult_SRC = insult.c
lineup_SRC = lineup.c
matmult_SRC = matmult.c
recursor_SRC = recursor.c
shell_SRC = shell.c
ls_SRC = ls.c
mkdir_SRC = mkdir.c

include $(SRCDIR)/Makefile.userprog
