SRCDIR = ../..

# Test programs to compile, and a list of sources for each.
# To add a new test, put its name on the PROGS list
# and then add a name_SRC line that lists its source files.
PROGS = bubsort echo halt insult lineup matmult recursor shell
bubsort_SRC = bubsort.c
echo_SRC = echo.c
halt_SRC = halt.c
insult_SRC = insult.c
lineup_SRC = lineup.c
matmult_SRC = matmult.c
recursor_SRC = recursor.c
shell_SRC = shell.c

include $(SRCDIR)/Makefile.userprog

# Uncomment the line below to round up segment sizes to full pages for
# testing purposes only.
#LDFLAGS += -Wl,-T,fullpage.x
