\input texinfo                          @c -*- texinfo -*-
@c %**start of header
@setfilename pintos.info
@settitle Pintos Projects
@c %**end of header

@c @bibref{} macro
@iftex
@macro bibref{cite}
[\cite\]
@end macro
@end iftex
@ifinfo
@ifnotplaintext
@macro bibref{cite}
@ref{\cite\}
@end macro
@end ifnotplaintext
@ifplaintext
@macro bibref{cite}
[\cite\]
@end macro
@end ifplaintext
@end ifinfo
@ifhtml
@macro bibref{cite}
[@ref{\cite\}]
@end macro
@end ifhtml

@macro func{name}
@code{\name\()}
@end macro

@macro struct{name}
@code{struct \name\}
@end macro

@titlepage
@title Pintos
@author by Ben Pfaff
@author based on past contributions of CS 140 TAs
@end titlepage

@contents

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Pintos Projects
@end ifnottex

@menu
* Introduction::                
* Pintos Tour::
* Project 1--Threads::          
* Project 2--User Programs::    
* Project 3--Virtual Memory::   
* Project 4--File Systems::     
* References::
* Multilevel Feedback Scheduling::  
* Coding Standards::            
* Project Documentation::       
* Debugging Tools::             
* Development Tools::
@end menu

@include intro.texi
@include tour.texi
@include threads.texi
@include userprog.texi
@include vm.texi
@include filesys.texi
@include references.texi
@include mlfqs.texi
@include standards.texi
@include doc.texi
@include debug.texi
@include devel.texi

@bye
