@node Top, Introduction, (dir), (dir)
@top Pintos Projects

@menu
* Introduction::                
* Project 1--Threads::          
* Project 2--User Programs::    
* Project 3--Virtual Memory::   
* Project 4--File Systems::     
* Multilevel Feedback Scheduling::  
* Coding Standards::            
@end menu

@include intro.texi
@include threads.texi
@include userprog.texi
@include vm.texi
@include filesys.texi
@c @include devel.texi
@include mlfqs.texi
@include standards.texi
