@node References, Multilevel Feedback Scheduling, Project 4--File Systems, Top
@appendix References

@macro bibdfn{cite}
@noindent @anchor{\cite\}
[\cite\].@w{  }
@end macro

@menu
* Hardware References::     
* Software References::     
@end menu

@node Hardware References
@section Hardware References

@bibdfn{IA32-v1}
@uref{ftp://download.intel.com/design/Pentium4/manuals/25366515.pdf, ,
IA-32 Intel Architecture Software Developer's Manual Volume 1: Basic
Architecture}.  Basic 80@var{x}86 architecture and programming
environment.

@bibdfn{IA32-v2a}
@uref{ftp://download.intel.com/design/Pentium4/manuals/25366615.pdf, ,
IA-32 Intel Architecture Software Developer's Manual Volume 2A:
Instruction Set Reference A-M}.  80@var{x}86 instructions whose names
begin with A through M.

@bibdfn{IA32-v2b}
@uref{ftp://download.intel.com/design/Pentium4/manuals/25366715.pdf, ,
IA-32 Intel Architecture Software Developer's Manual Volume 2B:
Instruction Set Reference N-Z}.  80@var{x}86 instructions whose names
begin with N through Z.

@bibdfn{IA32-v3}
@uref{ftp://download.intel.com/design/Pentium4/manuals/25366815.pdf, ,
IA-32 Intel Architecture Software Developer's Manual Volume 3: System
Programming Guide}.  Operating system support, including segmentation,
paging, tasks, interrupt and exception handling.

@bibdfn{FreeVGA}
@uref{specs/freevga/home.htm, , FreeVGA Project}.  Documents the VGA video
hardware used in PCs.

@bibdfn{kbd}
@uref{specs/kbd/scancodes.html, , Keyboard scancodes}.  Documents PC keyboard
interface.

@bibdfn{ATA-3}
@uref{specs/ata-3-std.pdf, , AT Attachment-3 Interface (ATA-3) Working
Draft}.  Draft of an old version of the ATA aka IDE interface for the
disks used in most desktop PCs.

@bibdfn{PC16550D}
@uref{specs/pc16550d.pdf, , National Semiconductor PC16550D Universal
Asynchronous Receiver/Transmitter with FIFOs}.  Datasheet for a chip
used for PC serial ports.

@bibdfn{8254}
@uref{specs/8254.pdf, , Intel 8254 Programmable Interval Timer}.
Datasheet for PC timer chip.

@bibdfn{8259A}
@uref{specs/8259A.pdf, , Intel 8259A Programmable Interrupt Controller
(8259A/8259A-2)}.  Datasheet for PC interrupt controller chip.

@node Software References
@section Software References

@bibdfn{ELF1}
@uref{specs/elf.pdf, , Tool Interface Standard (TIS) Executable and
Linking Format (ELF) Specification Version 1.2 Book I: Executable and
Linking Format}.  The ubiquitous format for executables in modern Unix
systems.

@bibdfn{ELF2}
@uref{specs/elf.pdf, , Tool Interface Standard (TIS) Executable and
Linking Format (ELF) Specification Version 1.2 Book II: Processor
Specific (Intel Architecture)}.  80@var{x}86-specific parts of ELF.

@bibdfn{ELF3}
@uref{specs/elf.pdf, , Tool Interface Standard (TIS) Executable and
Linking Format (ELF) Specification Version 1.2 Book III: Operating
System Specific (UNIX System V Release 4)}.  Unix-specific parts of
ELF.

@bibdfn{SysV-ABI}
@uref{specs/sysv-abi-4.1.pdf, , System V Application Binary Interface:
Edition 4.1}.  Specifies how applications interface with the OS under
Unix.

@bibdfn{SysV-i386}
@uref{specs/sysv-abi-i386-4.pdf, , System V Application Binary 
Interface: Intel386 Architecture Processor Supplement: Fourth
Edition}.  80@var{x}86-specific parts of the Unix interface.

@bibdfn{SysV-ABI-update}
@uref{specs/sysv-abi-update.html/contents.html, , System V Application Binary
Interface---DRAFT---24 April 2001}.  A draft of a revised version of
@bibref{SysV-ABI} which was never completed.
