Testing priority donation.
If the statements printed below are all true, you pass.
This thread should have priority 30.  Actual priority: 30.
This thread should have priority 31.  Actual priority: 31.
acquire2: got the lock
acquire2: done
acquire1: got the lock
acquire1: done
acquire2, acquire1 must already have finished, in that order.
This should be the last line before finishing this test.
Priority donation test done.
