SRCDIR = ..

# Test programs to compile, and a list of sources for each.
# To add a new test, put its name on the PROGS list
# and then add a name_SRC line that lists its source files.
PROGS = cat cmp cp echo halt hex-dump ls mcp mkdir rm shell \
	bubsort insult lineup matmult recursor

cat_SRC = cat.c
cmp_SRC = cmp.c
cp_SRC = cp.c
echo_SRC = echo.c
halt_SRC = halt.c
hex-dump_SRC = hex-dump.c
ls_SRC = ls.c
mcp_SRC = mcp.c
mkdir_SRC = mkdir.c
rm_SRC = rm.c
shell_SRC = shell.c

bubsort_SRC = bubsort.c
insult_SRC = insult.c
lineup_SRC = lineup.c
matmult_SRC = matmult.c
recursor_SRC = recursor.c

include $(SRCDIR)/Makefile.userprog
