#! /usr/bin/perl

if (@ARGV != 2) {
    print "usage: copy_in src dst\n";
    exit 1;
}
($src, $dst) = @ARGV;
$size = -s $src;

system "../pad 512 < $src > scratch.bin";
exec "./run_qemu -cp $dst:$size";
