include Makefile.vars
BUILD_SUBDIRS = $(addprefix build/, $(SUBDIRS))
LN = ln
MKDIR = mkdir

all: build build/Makefile $(BUILD_SUBDIRS)
	$(MAKE) -C build

$(BUILD_SUBDIRS):
	$(MKDIR) $@
build:
	$(MKDIR) $@
build/Makefile: ../Makefile.build
	$(LN) -f $< $@

clean:
	rm -rf build
