# -*- makefile -*-

include Make.vars
BUILD_SUBDIRS = $(addprefix build/, $(SUBDIRS))
CP = cp
MKDIR = mkdir

all: build build/Makefile $(BUILD_SUBDIRS)
	$(MAKE) -C build

$(BUILD_SUBDIRS):
	$(MKDIR) $@
build:
	$(MKDIR) $@
build/Makefile: ../Makefile.build
	$(CP) $< $@

clean:
	rm -rf build
